name: Build and release android app

on:
  workflow_dispatch:
    inputs:
      version:
        description: "APP version"
        required: true

defaults:
  run:
    working-directory: android-app

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: |
          npm install
          npm run check
          npm run lint

  build-and-release:
    needs: check

    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v2

      - name: Set java sdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install npm dependencies
        run: |
          npm install

      - name: "Build Android apk"
        run: |
          cd android
          echo "${{ secrets.ANDROID_RELEASE_KEY }}" | LC_ALL=C tr -cd 0-9a-fA-F | xxd -r -p > ./app/${{ secrets.ANDROID_RELEASE_STORE_FILE }}
          echo "MYAPP_RELEASE_STORE_FILE=${{ secrets.ANDROID_RELEASE_STORE_FILE }}" >> keystore.properties
          echo "MYAPP_RELEASE_KEY_ALIAS==${{ secrets.ANDROID__RELEASE_KEY_ALIAS }}" >> keystore.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.ANDROID_RELEASE_STORE_PASSWORD }}" >> keystore.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}" >> keystore.properties
          bash ./gradlew assembleRelease --stacktrace

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          fail_on_unmatched_files: true
          files: |
            android-app/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
            android-app/android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            android-app/android/app/build/outputs/apk/release/app-x86_64-release.apk
            android-app/android/app/build/outputs/apk/release/app-x86-release.apk
