name: Publish power-app docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image version"
        required: true

defaults:
  run:
    working-directory: power-app

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: |
          npm install
          npm run check

  push:
    needs: check

    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: makeflowliuxing/power-app-call-recording-uploader
          tags: ${{ github.event.inputs.version }}
          path: power-app
