name: Publish power-app docker image

on:
  push:
    tags:
      - "power-app-v*"

defaults:
  run:
    working-directory: power-app

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: |
          npm install
          npm run check

  push:
    needs: check

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2
        id: getTagName
        with:
          tagRegex: "power-app-v(.*)"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: makeflow/power-app-call-recording-uploader
          tags: ${{ steps.getTagName.outputs.tag }}
          path: power-app
